version: '2'

services:

  php-fpm:
    build:
      context: ./docker/php-fpm
    depends_on:
      - postgres
#    network_mode:
#        "host"
    environment:
      - APP_ENV=dev
      - APP_SECRET=1230d0cc90e7bb6e17fbf72dbfb3b16c
#      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ./:/var/www

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
#    network_mode:
#        "host"
    depends_on:
      - php-fpm
    ports:
      - "80:80"

  postgres:
    image: postgres:11.5
    ports: 
        - "5432:5432"
    restart: always
    environment:
        - "POSTGRES_DB=postgres"
        - "POSTGRES_USER=postgres"
        - "POSTGRES_PASSWORD=postgres"

  rabbitmq:
    image: rabbitmq:3-management
    # network_mode: "host"
    expose:
      - "5672"
    ports:
      - "8080:15672"
    restart: always
